---
title: "Example datasets"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example datasets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(cardinalR)
library(langevitour)
```

Examples of different data structures that can be generated are shown below.

## Gaussian data

```{r}
gau_data <- gen_gaussian(n = 500, p = 4, m = c(0, 0, 0, 0), s = diag(4) * 0.01)

langevitour(gau_data, pointSize = 2)
```

## Grid data

```{r, eval=FALSE}
two_grd_data <- two_grid_comb_bkg(n_value = 15, num_noise = 2, min_n = -0.05, max_n = 0.05)
two_grd_data$n

colnames(two_grd_data$df) <- paste0("x", seq_len(NCOL(two_grd_data$df)))

langevitour(two_grd_data$df, pointSize = 2)
```

## Circular data

```{r, eval=FALSE}
curvy_cyc_data <- curvy_cycle(n = 300, num_noise = 2, min_n = -0.05, max_n = 0.05)

colnames(curvy_cyc_data) <- paste0("x", seq_len(NCOL(curvy_cyc_data)))

langevitour(curvy_cyc_data, pointSize = 2)
```

## Branching data

```{r}
tree_data <- gen_threebranches(n = c(200, 500, 300), p = 4) |>
  dplyr::select(-cluster)

langevitour(tree_data, pointSize = 2)
```

## Linear data

```{r, eval=FALSE}
four_linear_data <- four_long_clust(
  n = 500, num_noise = 2, min_n = -0.05,
  max_n = 0.05
)

colnames(four_linear_data) <- paste0("x", seq_len(NCOL(four_linear_data)))

langevitour(four_linear_data, pointSize = 2)
```

## Nonlinear data

```{r, eval=FALSE}
two_curvy_panckakes <- two_curvy_panckakes(
  n = 300, num_noise = 2, min_n = -0.05,
  max_n = 0.05
)

colnames(two_curvy_panckakes) <- paste0("x", seq_len(NCOL(two_curvy_panckakes)))

langevitour(two_curvy_panckakes, pointSize = 2)
```

## Sphere data

```{r}
sphere_data <- gen_gridedSphere(n = 20, p = 4, r = 1)

langevitour(sphere_data, pointSize = 2)
```

## Mobius with Gaussian cluster

```{r}
mobius_clust_data <- gen_mobiusGau(n = c(500, 100), p = 4) |>
  dplyr::select(-cluster)

langevitour(mobius_clust_data, pointSize = 2)
```

## Pyramid data

```{r}
pyr_data <- gen_pyrHoles(n = 500, p = 4)

langevitour(pyr_data, pointSize = 2)
```
